COUNTRY_PROFILES = {
    "DE": {
        "name": "Germany",
        "engineering_rate": 80.0,
        "assembly_rate": 45.0,
        "cnc_3_axis_rate": 110.0,
        "cnc_5_axis_rate": 145.0,
        "edm_rate": 115.0,
        "grinding_rate": 110.0,
        "electricity_eur_kwh": 0.226,
        "machine_efficiency": 0.82,
        "operator_efficiency": 0.88,
        "overhead_rate": 0.15,
        "margin_rate": 0.15,
    },

    "FR": {
        "name": "France",
        "engineering_rate": 75.0,
        "assembly_rate": 43.0,
        "cnc_3_axis_rate": 105.0,
        "cnc_5_axis_rate": 140.0,
        "edm_rate": 115.0,
        "grinding_rate": 110.0,
        "electricity_eur_kwh": 0.153,
        "machine_efficiency": 0.82,
        "operator_efficiency": 0.88,
        "overhead_rate": 0.15,
        "margin_rate": 0.15,
    },

    "AT": {
        "name": "Austria",
        "engineering_rate": 85.0,
        "assembly_rate": 47.0,
        "cnc_3_axis_rate": 110.0,
        "cnc_5_axis_rate": 145.0,
        "edm_rate": 120.0,
        "grinding_rate": 115.0,
        "electricity_eur_kwh": 0.199,
        "machine_efficiency": 0.82,
        "operator_efficiency": 0.88,
        "overhead_rate": 0.15,
        "margin_rate": 0.15,
    },

    "CZ": {
        "name": "Czech Republic",
        "engineering_rate": 35.0,
        "assembly_rate": 19.0,
        "cnc_3_axis_rate": 80.0,
        "cnc_5_axis_rate": 115.0,
        "edm_rate": 85.0,
        "grinding_rate": 85.0,
        "electricity_eur_kwh": 0.183,
        "machine_efficiency": 0.82,
        "operator_efficiency": 0.88,
        "overhead_rate": 0.15,
        "margin_rate": 0.15,
    },

    "SK": {
        "name": "Slovakia",
        "engineering_rate": 30.0,
        "assembly_rate": 18.0,
        "cnc_3_axis_rate": 80.0,
        "cnc_5_axis_rate": 115.0,
        "edm_rate": 85.0,
        "grinding_rate": 80.0,
        "electricity_eur_kwh": 0.209,
        "machine_efficiency": 0.82,
        "operator_efficiency": 0.88,
        "overhead_rate": 0.15,
        "margin_rate": 0.15,
    },

    "HU": {
        "name": "Hungary",
        "engineering_rate": 25.0,
        "assembly_rate": 14.0,
        "cnc_3_axis_rate": 75.0,
        "cnc_5_axis_rate": 110.0,
        "edm_rate": 85.0,
        "grinding_rate": 80.0,
        "electricity_eur_kwh": 0.213,
        "machine_efficiency": 0.82,
        "operator_efficiency": 0.88,
        "overhead_rate": 0.15,
        "margin_rate": 0.15,
    },

    "PL": {
        "name": "Poland",
        "engineering_rate": 30.0,
        "assembly_rate": 16.0,
        "cnc_3_axis_rate": 75.0,
        "cnc_5_axis_rate": 115.0,
        "edm_rate": 85.0,
        "grinding_rate": 80.0,
        "electricity_eur_kwh": 0.192,
        "machine_efficiency": 0.82,
        "operator_efficiency": 0.88,
        "overhead_rate": 0.15,
        "margin_rate": 0.15,
    },

    "ES": {
        "name": "Spain",
        "engineering_rate": 45.0,
        "assembly_rate": 26.0,
        "cnc_3_axis_rate": 85.0,
        "cnc_5_axis_rate": 120.0,
        "edm_rate": 95.0,
        "grinding_rate": 90.0,
        "electricity_eur_kwh": 0.132,
        "machine_efficiency": 0.82,
        "operator_efficiency": 0.88,
        "overhead_rate": 0.15,
        "margin_rate": 0.15,
    },

    "IT": {
        "name": "Italy",
        "engineering_rate": 55.0,
        "assembly_rate": 30.0,
        "cnc_3_axis_rate": 90.0,
        "cnc_5_axis_rate": 130.0,
        "edm_rate": 100.0,
        "grinding_rate": 95.0,
        "electricity_eur_kwh": 0.220,
        "machine_efficiency": 0.82,
        "operator_efficiency": 0.88,
        "overhead_rate": 0.15,
        "margin_rate": 0.15,
    },

    "CN": {
        "name": "China",
        "engineering_rate": 25.0,
        "assembly_rate": 10.0,
        "cnc_3_axis_rate": 65.0,
        "cnc_5_axis_rate": 100.0,
        "edm_rate": 75.0,
        "grinding_rate": 70.0,
        "electricity_eur_kwh": 0.090,
        "machine_efficiency": 0.82,
        "operator_efficiency": 0.88,
        "overhead_rate": 0.15,
        "margin_rate": 0.15,
    },

    "IN": {
        "name": "India",
        "engineering_rate": 15.0,
        "assembly_rate": 5.0,
        "cnc_3_axis_rate": 60.0,
        "cnc_5_axis_rate": 95.0,
        "edm_rate": 70.0,
        "grinding_rate": 65.0,
        "electricity_eur_kwh": 0.070,
        "machine_efficiency": 0.82,
        "operator_efficiency": 0.88,
        "overhead_rate": 0.15,
        "margin_rate": 0.15,
    },
}